channels:
  - defaults
  - cadquery
  - conda-forge
  - set3mah
dependencies:
  - python=3.9
  - pip=21.0
  - cadquery=master
  - ipyvtklink
  - microgen
  - jupyterlab
  - pip:
      - jupyter-cadquery==3.0.0
