name: env
channels:
  # - set3mah
  # - cadquery
  - conda-forge
  - defaults
dependencies:
  # - cadquery=master
  - gmsh=4.8.4
  - meshio=5.3.4
  # - microgen=1.0.0
  # - mmg=5.6.0
  - numpy=1.22.3
  - pip=22.0.4
  - pygalmesh=0.10.6
  - python=3.9.12
  - python-gmsh=4.8.4
  - vtk=9.0.1
