name: 3mah
channels:
  - conda-forge
  # - cadquery
  # - set3MAH
dependencies:
  - python=3.9
  - pip
  - setuptools
  - ipykernel
  - jupyterlab
  - ipyvtklink
  # - microgen
  - pip:
    - jupyter_cadquery
