name: env
channels:
  - set3mah
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cadquery=master
  - cftime=1.6.0
  - colorama=0.4.4
  - commonmark=0.9.1
  - curl=7.82.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.1.1
  - double-conversion=3.1.7
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.4.7
  - ezdxf=0.17.2
  - ffmpeg=4.3.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - gmp=6.2.1
  - gmsh=4.8.4
  - gnutls=3.6.13
  - gst-plugins-base=1.20.1
  - gstreamer=1.20.1
  - h5py=3.3.0
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=69.1
  - ilmbase=2.5.5
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - ipython=8.1.1
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9e
  - jsoncpp=1.9.4
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libglu=9.0.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.2
  - libraw=0.20.2
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - loguru=0.5.3
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.3
  - meshio=5.3.4
  - microgen=1.0.0
  - mmg=5.6.0
  - mpfr=4.1.0
  - multimethod=1.6
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - ncurses=6.3
  - netcdf4=1.5.7
  - nettle=3.6
  - nlopt=2.7.1
  - nptyping=1.4.4
  - nspr=4.32
  - nss=3.76
  - numpy=1.22.3
  - occt=7.5.3
  - ocp=7.5.3.0
  - openexr=2.5.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.0.4
  - proj=7.2.0
  - prompt-toolkit=3.0.27
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pygalmesh=0.10.6
  - pygments=2.11.2
  - pyparsing=3.0.7
  - python=3.9.12
  - python-gmsh=4.8.4
  - python_abi=3.9
  - qt=5.12.9
  - rapidjson=1.1.0
  - readline=8.1
  - rich=12.0.1
  - setuptools=60.10.0
  - six=1.16.0
  - sqlite=3.37.1
  - stack_data=0.2.0
  - tbb=2020.2
  - tbb-devel=2020.2
  - tk=8.6.12
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - typish=1.9.3
  - tzdata=2022a
  - utfcpp=3.2.1
  - vtk=9.0.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!161.3030
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxmu=1.1.3
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
